# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0003_auto_20180226_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='goal',
            field=models.CharField(choices=[('Gain weight', 'Gain weight'), ('Loose weight', 'Loose weight'), ('Stay Fit', 'Stay Fit')], default='Loose weight', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lifestyle',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active'), ('Extremely active', 'Extremely active')], default='Moderately active', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='medical_history',
            field=models.CharField(choices=[('Diabities', 'Diabities'), ('Hypothyroidism', 'Hypothyroidism'), ('None', 'None')], default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('GIFW', 'Graduate/Intern/Fresher Job/Work from Home'), ('Corporate Work', 'Corporate Work'), ('MEG', 'Medical/Education/Governmental work'), ('PLW', 'Physical Labour Work')], default='Student', max_length=50),
        ),
    ]
