# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dietplan', '0004_auto_20180226_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(default=1, max_length=255)),
                ('email_validated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='food_preference',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg'), ('VE', 'Veg including Egg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='goal',
            field=models.CharField(choices=[('Gain weight', 'Gain weight'), ('Loose weight', 'Loose weight'), ('Stay Fit', 'Stay Fit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lifestyle',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active'), ('Extremely active', 'Extremely active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='medical_history',
            field=models.CharField(choices=[('Diabities', 'Diabities'), ('Hypothyroidism', 'Hypothyroidism'), ('None', 'None')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('GIFW', 'Graduate/Intern/Fresher Job/Work from Home'), ('Corporate Work', 'Corporate Work'), ('MEG', 'Medical/Education/Governmental work'), ('PLW', 'Physical Labour Work')], max_length=50),
        ),
    ]
