# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0006_auto_20180324_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'UserDetails'},
        ),
    ]
