# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0008_userdetails_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='medical_history',
            field=models.CharField(choices=[('Diabities', 'Diabities'), ('Hypothyroidism', 'Hypothyroidism'), ('None', 'None'), ('Cholesterol', 'Cholesterol')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Graduate/Intern/Fresher Job/Work from Home', 'Graduate/Intern/Fresher Job/Work from Home'), ('Corporate Work', 'Corporate Work'), ('Medical/Education/Governmental work', 'Medical/Education/Governmental work'), ('Physical Labour Work', 'Physical Labour Work')], max_length=50),
        ),
    ]
