# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0009_auto_20180404_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='medical_history',
            field=models.CharField(choices=[('None', 'None'), ('Diabities', 'Diabities'), ('Hypothyroidism', 'Hypothyroidism'), ('Cholesterol', 'Cholesterol')], max_length=40),
        ),
    ]
