# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0010_auto_20180404_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='food_preference',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg'), ('Veg including Egg', 'Veg including Egg')], max_length=20),
        ),
    ]
