# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0014_auto_20180408_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 17, 43, 10, 535853, tzinfo=utc)),
        ),
    ]
